# Generated by Django 5.1.7 on 2025-03-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TikTokCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("objective", models.CharField(default="REACH", max_length=100)),
                ("status", models.CharField(default="INACTIVE", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TikTokCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creative_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("creative_type", models.CharField(default="IMAGE", max_length=50)),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the uploaded creative on TikTok",
                        null=True,
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path before upload",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="marketing.tiktokcampaign",
                    ),
                ),
            ],
        ),
    ]
